# Generated by Django 3.0.7 on 2021-08-29 04:19

import App1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=3, unique=True)),
                ('name', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to=App1.models.Student.uploaddoc)),
            ],
        ),
    ]
